export const ADD_ORDER_TO_CART = "ADD_ORDER_TO_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const DELETE_ORDER = "DELETE_ORDER";
